### PR TITLE
Copy files feature

### PR DESCRIPTION
**Pull request by cevich**
was #95

### CODE REVIEW

**Comment by cevich** [comment]
N.B. This will need to be rebased after applying #99 b/c ``group_vars/fedoratomic/autotested.yml`` conflicts.

**Comment by cevich** [comment]
rebased and force-pushed

**Comment by cevich** [comment]
Note to me: Need to double-check this really is working w/o the temporary (external) copying of ``known_vailures.csv``.  Setup console from CI run shows copyfiles task is working fine.

**Comment by cevich** [comment]
@edsantiago anything you want to review here? This PR is against devel (with yumrepos fix).  It implements the feature needed to deploy your ``known_failures.csv``.  Also some needed changes to the ``autotested`` role which will make migrating it into ``simplify`` easier.

**Comment by cevich** [comment]
ugg, ``--force`` pushed again after rebasing on master.

**Comment by edsantiago** [comment]
No, I looked at this when you first pushed it but it's far too complicated for me to review; far beyond my abilities.

**Comment by cevich** [comment]
okie dokie, I'll merge and we'll move forward on ``simplify`` where you've got at least one hand in the pie and many more neurons in alignment 😀

**Pull request merged**
